name: freemework
description: Common library of the Freemework.
version: 0.1.0
homepage: https://freemework.org
repository: https://github.com/freemework/dart
issue_tracker: https://github.com/freemework/dart/issues
documentation: https://freemework.org/#common?lang=dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  build_runner: ^1.11.1
  build_test: ^1.3.6
  pedantic: ^1.9.2
  test: ^1.15.7
